name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature
      placeholder: What do you want to add?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe the solution you'd like
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: Affected Service(s)
      description: Which service(s) would this feature affect?
      multiple: true
      options:
        - user-service
        - product-service
        - order-service
        - payment-service
        - inventory-service
        - notification-service
        - api-gateway
        - frontend
        - infrastructure
        - new service needed
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High (critical for MVP)
        - Medium (important but not blocking)
        - Low (nice to have)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
      placeholder: Describe any alternative solutions or features you've considered

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots
